Switch to pkg-config
metabrainz/postgresql-musicbrainz-collate pull request #5
Opened 2020-01-20 10:49 UTC by SuperSandro2000

Debian Buster no longer ships ico-config.

2020-01-20 15:29 UTC, yvanzo requested changes
Thank you for this patch.

- [x] `README.musicbrainz_collate.md` file should be updated too.
- [ ] <del>`debian/` should be updated if possible (not sure it is actually used though).</del>
      (Edit: `debian/` packaging is not currently used and outdated anyway)

 I just opened pull requests to prepare dependent repositories for this change.

2020-01-20 22:08 UTC, SuperSandro2000 commented
I didn't find a icu-config reference in the debian directory.

2020-01-21 09:52 UTC, yvanzo approved these changes

2020-01-22 23:26 UTC, mwiencek approved these changes
This works fine on macOS too.

2020-01-27 19:57 UTC, zas approved these changes
Lgtm

2020-01-27 20:23 UTC, merged